### ISSUE TITLE
Review helpers

### ISSUE THREAD

**Issue by TudorHulban** [cezarovici/goLayouter#7]
some helpers might not belong to the helpers, ex. :+
https://github.com/cezarovici/goLayouter/blob/master/helpers/line_operations.go#L77   

please review DDD and come with a proposal in a PR.  
I would say we could create a service.

**Comment by cezarovici** [comment]
I don't think this should be moved, maybe renamed but I consider this is ok. Please check out where I use it

1.https://github.com/cezarovici/goLayouter/blob/5b0490052d47e2f779c53e6409c2d8137759a3db/helpers/line_operations.go#L77

2.https://github.com/cezarovici/goLayouter/blob/5b0490052d47e2f779c53e6409c2d8137759a3db/domain/line/line.go#L170

**Comment by TudorHulban** [comment]
as a rule of thumb, helpers package in an app should not contain internal dependencies.  
of course, helpers can exist at a package level. these helpers should support only objects within that package.  

it is objects that interact with other objects, we are not working imperative due to the size of apps we are targeting.
